apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: quay.io/karthikrajdev99/ecommerce_node:2.1
          env:
            - name: PREFIX
              value: "nodes"
          envFrom:
            - secretRef:
                name: nodesecret5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
